### ISSUE TITLE
Featured request, polish badwords

### ISSUE THREAD

**Issue by ToAruShiroiNeko** [wiki-ai/revscoring#131]
https://en.wikipedia.org/w/index.php?title=Wikipedia:Sandbox&action=edit&oldid=671804402

**Comment by Ladsgroup** [comment]
Sure, Starting BWDS to generate bad words

**Comment by Ladsgroup** [comment]
https://gist.github.com/Ladsgroup/cc22515f55ae3d868f47#file-plwiki

**Comment by halfak** [comment]
Still waiting on a native speaker to help us out here: https://meta.wikimedia.org/wiki/Research:Revision_scoring_as_a_service/Word_lists/pl
