### ISSUE TITLE
Travis CI is broken due to scipy install

### ISSUE THREAD

**Issue by adamwight** [wiki-ai/revscoring#145]
The script hangs for over 10 minutes while provisioning scipy: https://travis-ci.org/wiki-ai/revscoring/builds/73266170 -- It's been borken forever, https://travis-ci.org/wiki-ai/revscoring/builds

There's a warning about "upgrade to our new infrastructure", fwiw.

Here's a workaround from 2014, looks like it's still necessary to do something like this.  https://gist.github.com/dan-blanchard/7045057

**Comment by halfak** [comment]
I turned travis-ci off today since it was so bothersome.
