### ISSUE TITLE
Many Portuguese badwords are not recognized anymore

### ISSUE THREAD

**Issue by he7d3r** [wiki-ai/revscoring#170]
Since we are not using stemming anymore, and the badwords list generated for Portuguese was originally created based on stems (21e410f), excluding variations of each word (when its stem was the same as the stem of a word which would be kept in the list), these variations are not recognized as badwords anymore.

For example:

``` python
>>> from revscoring.languages import portuguese
>>> [ portuguese.is_badword(x) for x in [ "mentiroso", "mentirosa", "mentirosos", "mentirosas" ] ]
[True, False, True, False]
```

This was the raw badwords list used in the filtering process:
https://gist.github.com/he7d3r/7e3718a43f5ce65e0dab
This was the script used for filtering:
https://gist.github.com/he7d3r/de5af63ac04338c3bfbf#file-stemtomostfrequentword-py

**Comment by halfak** [comment]
I added these particular badwords back in https://github.com/wiki-ai/revscoring/pull/179

But that doesn't solve the general problem.  We might need to use a hybrid of stemming/regex to get the both the coverage we had before and the flexibility that regex provides.

**Comment by he7d3r** [comment]
https://github.com/wiki-ai/revscoring/pull/228 might help with this.

**Comment by halfak** [comment]
Looks like this was resolved a long time ago
