### ISSUE TITLE
Set-based badwords and misspellings detection

### ISSUE THREAD

**Issue by halfak** [wiki-ai/revscoring#213]
It occurs to me that using set operation to detect the introduction of new types of badwords, informals and misspellings might have higher signal than using the content of the diff.  

E.g. revision.badwords_set - parent_revision.badwords_set = new_badwords_set

If the last revision contained an instance of the curse "shit", and the editor added a new instance of the word "shit" the set difference would empty.  But if the editor added an instance of the word "fuck" then that would show up since it wasn't in the article before.  

These types of features should be pretty easy to add to the SpaceDelimited metafeatures.  See https://github.com/wiki-ai/revscoring/blob/master/revscoring/languages/space_delimited/space_delimited.py#L14

**Comment by halfak** [comment]
One more note.  If we could switch entirely away from diff-based features, then we wouldn't need to perform diff operations at all!  This would substantially reduce the amount of CPU time we need for scoring a revision.

**Comment by he7d3r** [comment]
But then vandals using the same badwords already in the article would no be noticed, right? E.g. edit to articles such as https://en.wikipedia.org/w/index.php?oldid=690934073

**Comment by halfak** [comment]
Yes.  That's right.  It seems that this would be a desirable trade-off.  After all, I suspect that it is likely that vandals will add new badwords to the article you mention when vandalizing it.

**Comment by halfak** [comment]
This is now implemented as term frequency features. :)
