### ISSUE TITLE
Profiling feature extractor

### ISSUE THREAD

**Issue by halfak** [wiki-ai/revscoring#234]
Some features require more computation/IO than others.  It should be possible to run some sample data through an extractor and get some basic statistics about how long each feature takes to generate -- both the cost of dependencies and the cost of local computation should be reported.  

E.g. `cat some_revisions.tsv | revscoring extract_features my_project.my_features --profile my_profile.md` should produce a markdown file that looks roughly like:
## Performance
- Features: 54
- Observations: 19982
### Extraction
- Total time: 01:20:25.5
- Avg: 0.241(s)
- Min: 0.030(s)
- Max: 14.5(s)
- 95%: 2.10(s)
- 5%: 0.151(s)
### IO time
- Total time: 00:45:52.5
- Avg: 0.136(s)
- Min: 0.320(s)
- Max: 2.59(s)
- 95%: 1.10(s)
- 5%: 0.401(s)
### CPU time
- Total time: 00:35:03.1
- Avg: 0.105(s)
- Min: 0.000(s)
- Max: 13.5(s)
- 95%: 12.9(s)
- 5%: 0.015(s)
## Features

| dependent | process() time | dependencies time | total time |
| --- | --- | --- | --- |
| revision.wikitext.revision.diff.words_added | < .001 | 0.563 | 0.563 |
| english.dictionary.revision.diff.dict_word_delta_sum | < .001 | 0.502 | 0.502 |

...
## Datasources

| dependent | process() time | dependencies time | total time |
| --- | --- | --- | --- |
| english.dictionary.revision.dict_words | 0.15 | 0.101 | 0.251 |
| english.dictionary.revision.dict_word_frequency | < .001 | 0.251 | 0.251 |
| english.dictionary.revision.parent.dict_words | 0.149 | 0.102 | 0.251 |
| english.dictionary.revision.parent.dict_word_frequency | < .001 | 0.251 | 0.251 |
| english.dictionary.revision.diff.dict_word_delta | < .001 | 0.502 | 0.502 |

...

**Comment by jonasagx** [comment]
Is there someone already working on this? It sounds interesting. I would like to make it.

**Comment by halfak** [comment]
hey @jonasagx!  It turns out that we've already implemented this in https://github.com/wiki-ai/revscoring/commit/b9867e23ef89d84e82a10acf71a1bc79f5015356.  I'd just forgot to close it.  Maybe you'd be interested in working on some optimizations based on the profiler's output instead.

**Comment by jonasagx** [comment]
Cool @halfak! How can I dig into it? Is @he7d3r or @Ladsgroup  aware of it? These days I have more free time so I would like to work on it. Thanks for your help.

**Comment by halfak** [comment]
Indeed @he7d3r or @Ladsgroup should be aware.  I think that it'll be easiest for me to work with you to run a profiling job over IRC.  Would you be available to meet in #wikimedia-ai on freenode between 1500 and 0200 UTC some time this week?

**Comment by jonasagx** [comment]
Coo! I'm free to talk between these hours. I think we are on the same timezone. I am at PST (UTC-8). What about today? 2200 UTC (1400 PST)?

I'm trying to set up my development env. I installed revscoring via pip and have all the dependencies in a virtualenv with Python 3.5.2. That's how you do?

**Comment by halfak** [comment]
sorry I've missed you on IRC.  It'll be easier to do these things synchronously.  I'm in CST (UTC-6) and am around today at 2200 UTC.
